# Forestry data preprocessing

In this notebook we prepare and clean the forestry data.

First, we load the data.

In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
file1 = "ХМАО/ХМАО_polygons_ЗЛФ.shp"
file1 = gpd.read_file(file1)

In [3]:
file2 = "ХМАО/ХМАО_polygons_ООПТ.shp"
file2 = gpd.read_file(file2)

In [4]:
file = pd.concat([file1, file2])

In [8]:
file.to_file("hmao_forestry_init.gpkg")

In [2]:
file = gpd.read_file("hmao_forestry_init.gpkg")

In [3]:
file.head()

,SRI,Lr,MU,GIR,Ugir,Mk,Rel,Kv,Sknr,Pl,...,Amz1,Akl,Bon,Mtip,Dtg,Skal1,Tur1h1,Strata,Izm,geometry
0,87,14,3,3,2,305000,1,335,6.0,3.1,...,135,7,51.0,КСФ,None,0.6,100,12,0,"MULTIPOLYGON (((62.33137 63.80387, 62.33062 63..."
1,87,15,4,6,14,204100,1,81,35.0,9.5,...,165,9,51.0,ОСКСФ,None,0.5,90,12,0,"MULTIPOLYGON (((64.88972 59.42719, 64.88878 59..."
2,87,15,4,6,14,204100,1,79,43.0,22.6,...,75,4,52.0,ОСКСФ,None,0.4,25,6,0,"MULTIPOLYGON (((64.78062 59.4423, 64.78328 59...."
3,87,15,4,6,14,204100,1,80,39.0,4.6,...,175,9,3.0,ЗМТЯГ,None,0.6,250,20,0,"MULTIPOLYGON (((64.82868 59.42363, 64.82945 59..."
4,87,14,3,3,2,305000,1,333,5.0,7.9,...,135,7,52.0,КСФ,None,0.4,35,12,0,"MULTIPOLYGON (((62.24469 63.80196, 62.2441 63...."

## Fixing the data

We explore the variables we need and fill nodata values.

In [4]:
file["Vmr"].unique()

array(['100150', '100345', '302620', '100508', '100215', '304403', None,
       '802694', '100440', '804330', '304000', '304303', '0', '304410',
       '504025', '00000', '304305', '000000', '100240', '304315',
       '304105', '0000'], dtype=object)

In [5]:
# Fillna
file["Vmr"] = file["Vmr"].fillna("0")

In [6]:
file["Vmr"].unique()

array(['100150', '100345', '302620', '100508', '100215', '304403', '0',
       '802694', '100440', '804330', '304000', '304303', '304410',
       '504025', '00000', '304305', '000000', '100240', '304315',
       '304105', '0000'], dtype=object)

In [7]:
file["Bon"].unique()

array([51., 52.,  3.,  5.,  4.,  0.,  2.,  1., nan, 12., 11.])

In [8]:
# Fillna
file["Bon"] = file["Bon"].fillna(0.)

In [9]:
file["Bon"].unique()

array([51., 52.,  3.,  5.,  4.,  0.,  2.,  1., 12., 11.])

For forest types we need to fix the encoding of some of the values.

In [10]:
file["Mtip"].unique()

array(['КСФ', 'ОСКСФ', 'ЗМТЯГ', 'БГБР', 'ТРБ', 'ДМХВ', 'ОССФ', '00000',
       'ПР', 'КЛШ', 'ЕРН', 'БГБРМ', 'ТБ', 'КРТ', 'БРБГМ', 'ХВ', 'БР', 'П',
       'ЗММТ', 'МШ', 'ЛШ', 'ЗМЯГ', '0', 'МШЯГ', 'ДМСФ', 'КМ', 'БГРМ',
       'ЗММЯГ', 'КОССФ', 'БРБГ', 'НГ', None, 'МШРТ', 'ХВМШ', 'РТ',
       'ОСЕРН', 'БГБГМ', '00', 'ЧР', 'ЛШБР', 'МШМП', 'Ч', 'мшяг', 'КООСФ',
       'ос', 'СФ', 'БГГБР', 'ОЛ', 'ЛБР', 'МЛК', 'ДМ', 'ЛОГ', 'мш',
       'БРГБМ', 'ГБМ', 'БРБМ', 'ЗМРТ', 'брбгм', 'нГ', 'ОСЕРн', 'КТРМШ',
       'ХВП', 'МШХВ', 'ШТ', 'МЯ', '0000000', 'ЕРн', 'ХВОСФ', 'В',
       'КООССФ', 'О', 'хв', 'ЗЯ', 'Л', '0000', '2', 'ЗМ', 'ЗМЯ', 'БРБ',
       'ЗММ', 'ОСС', 'ДМХ', 'БГБ', 'ЛШБ', 'ХВОС', 'ББР', 'БСФ', 'ДСФ',
       'Д', 'РТВ', 'ЛБХВ', 'лшбр', 'ДЬХВ', 'РљР\xa0Рў', 'Р‘Р\xa0',
       'Р—РњРњ', 'РћРЎРЎ', 'РџР\xa0', 'Р—РњРЇ', 'РљРЎР¤', 'Р‘Р“Р‘',
       'Р”РњРҐ', 'РўР\xa0Р‘', 'Р‘Р\xa0Р‘', 'Р\xa0Рў', 'Рџ', 'Р›РЁР‘',
       'Р›РЁ', 'ксф', 'бр', 'РҐР’', 'Р§Р\xa0', 'ЧКС', 'ТР', 'ЗЯГ', 'ОС',
       'КС', 'БГ', 'БО', 'КЛ', 'клш', 'КССФ', 'БРЯГ', 'змяг', 'ЧЗМ',
       'ХДГ', 'КЧДГ', 'КЧЗМ', 'МТЗМ', 'КЧСФ', 'БРЛШ', 'БРЗМ', 'ЯЗ', 'ЧЗ',
       'ОСДГ', 'ХЗМ', 'ЛШЗМ', 'ЗМСФ', 'КЗМ', 'КЧЛШ', 'БЗ', 'КТЗМ', 'ЛШСФ',
       'БС', 'МЗ', 'ПМ', 'БЛ', 'ХВЗМ', 'ПП', 'ОККСФ'], dtype=object)

In [11]:
# Fillna
file["Mtip"] = file["Mtip"].fillna("0")

In [12]:
def fix_encoding(val):
    try:
        # Try re-encoding
        fixed = val.encode("windows-1251").decode("utf-8")
        # Optional: Add logic to compare val vs fixed and decide whether to return fixed
        return fixed
    except (UnicodeEncodeError, UnicodeDecodeError):
        # If encoding fails, return original
        return val

# Apply to the Mtip column
file["Mtip"] = file["Mtip"].apply(fix_encoding)

In [13]:
file["Mtip"].unique()

array(['КСФ', 'ОСКСФ', 'ЗМТЯГ', 'БГБР', 'ТРБ', 'ДМХВ', 'ОССФ', '00000',
       'ПР', 'КЛШ', 'ЕРН', 'БГБРМ', 'ТБ', 'КРТ', 'БРБГМ', 'ХВ', 'БР', 'П',
       'ЗММТ', 'МШ', 'ЛШ', 'ЗМЯГ', '0', 'МШЯГ', 'ДМСФ', 'КМ', 'БГРМ',
       'ЗММЯГ', 'КОССФ', 'БРБГ', 'НГ', 'МШРТ', 'ХВМШ', 'РТ', 'ОСЕРН',
       'БГБГМ', '00', 'ЧР', 'ЛШБР', 'МШМП', 'Ч', 'мшяг', 'КООСФ', 'ос',
       'СФ', 'БГГБР', 'ОЛ', 'ЛБР', 'МЛК', 'ДМ', 'ЛОГ', 'мш', 'БРГБМ',
       'ГБМ', 'БРБМ', 'ЗМРТ', 'брбгм', 'нГ', 'ОСЕРн', 'КТРМШ', 'ХВП',
       'МШХВ', 'ШТ', 'МЯ', '0000000', 'ЕРн', 'ХВОСФ', 'В', 'КООССФ', 'О',
       'хв', 'ЗЯ', 'Л', '0000', '2', 'ЗМ', 'ЗМЯ', 'БРБ', 'ЗММ', 'ОСС',
       'ДМХ', 'БГБ', 'ЛШБ', 'ХВОС', 'ББР', 'БСФ', 'ДСФ', 'Д', 'РТВ',
       'ЛБХВ', 'лшбр', 'ДЬХВ', 'ксф', 'бр', 'ЧКС', 'ТР', 'ЗЯГ', 'ОС',
       'КС', 'БГ', 'БО', 'КЛ', 'клш', 'КССФ', 'БРЯГ', 'змяг', 'ЧЗМ',
       'ХДГ', 'КЧДГ', 'КЧЗМ', 'МТЗМ', 'КЧСФ', 'БРЛШ', 'БРЗМ', 'ЯЗ', 'ЧЗ',
       'ОСДГ', 'ХЗМ', 'ЛШЗМ', 'ЗМСФ', 'КЗМ', 'КЧЛШ', 'БЗ', 'КТЗМ', 'ЛШСФ',
       'БС', 'МЗ', 'ПМ', 'БЛ', 'ХВЗМ', 'ПП', 'ОККСФ'], dtype=object)

In [25]:
file["Dtg"].unique()

array([None, '00000', '2011', '2031', '2034', '2021', '2042', '2022',
       '2032', '2012', '2041', '2033', '3041', '3034', '3032', '3022',
       '3042', '3031', '3021', '3033', '3023', '3011', '0', '3012', 'С',
       'B4', 'C3', 'A5', 'C2', '331', 'С4', 'C1', 'В4', 'А5', '322',
       '332', '334', '321', '342', '341', '312', 'А2', 'С5', '311', '333',
       'A3', 'С3', 'B3', '0000', '00', '2023', '2025', '000'],
      dtype=object)

In [26]:
file["Dtg"] = file["Dtg"].fillna('00000')

In [27]:
file["Dtg"].unique()

array(['00000', '2011', '2031', '2034', '2021', '2042', '2022', '2032',
       '2012', '2041', '2033', '3041', '3034', '3032', '3022', '3042',
       '3031', '3021', '3033', '3023', '3011', '0', '3012', 'С', 'B4',
       'C3', 'A5', 'C2', '331', 'С4', 'C1', 'В4', 'А5', '322', '332',
       '334', '321', '342', '341', '312', 'А2', 'С5', '311', '333', 'A3',
       'С3', 'B3', '0000', '00', '2023', '2025', '000'], dtype=object)

In [35]:
file.to_file("hmao_forestry_init_fixed.gpkg")

## Re-mapping the values

Most of the values are use special forestry codes instead of human-readable values. We re-map these codes to more understandable format.

In [2]:
file = gpd.read_file("hmao_forestry_init_fixed.gpkg")

In [19]:
file.head()

,SRI,Lr,MU,GIR,Ugir,Mk,Rel,Kv,Sknr,Pl,...,Amz1,Akl,Bon,Mtip,Dtg,Skal1,Tur1h1,Strata,Izm,geometry
0,87,14,3,3,2,305000,1,335,6.0,3.1,...,135,7,51.0,КСФ,00000,0.6,100,12,0,"MULTIPOLYGON (((62.33137 63.80387, 62.33062 63..."
1,87,15,4,6,14,204100,1,81,35.0,9.5,...,165,9,51.0,ОСКСФ,00000,0.5,90,12,0,"MULTIPOLYGON (((64.88972 59.42719, 64.88878 59..."
2,87,15,4,6,14,204100,1,79,43.0,22.6,...,75,4,52.0,ОСКСФ,00000,0.4,25,6,0,"MULTIPOLYGON (((64.78062 59.4423, 64.78328 59...."
3,87,15,4,6,14,204100,1,80,39.0,4.6,...,175,9,3.0,ЗМТЯГ,00000,0.6,250,20,0,"MULTIPOLYGON (((64.82868 59.42363, 64.82945 59..."
4,87,14,3,3,2,305000,1,333,5.0,7.9,...,135,7,52.0,КСФ,00000,0.4,35,12,0,"MULTIPOLYGON (((62.24469 63.80196, 62.2441 63...."

### Vmr - dominant tree species

In [20]:
file["Vmr"].unique()

array(['100150', '100345', '302620', '100508', '100215', '304403', '0',
       '802694', '100440', '804330', '304000', '304303', '304410',
       '504025', '00000', '304305', '000000', '100240', '304315',
       '304105', '0000'], dtype=object)

In [21]:
file["Vmr"].value_counts()

Vmr
100150    775780
0         420778
302620    258678
100508    214605
100215     78377
304000     48719
000000     37571
100240     37537
100440     23055
304403     14567
304410      6905
100345      3526
802694      1915
804330      1215
304303       336
504025        65
00000         28
304315        21
304305         1
304105         1
0000           1
Name: count, dtype: int64

In [24]:
specs = {
    1: ['', '0', '000000', '00000', '0000',], # Non-forest areas
    2: ['С', '100150'], # Сосна - Pine
    3: ['Л', '100440'], # Лиственица - Larch
    4: ['К', '100508'], # Кедр - Siberian Pine
    5: ['Е', '100215', '100240'], # Ель - Spruce
    6: ['П', '100345'], # Пихта - Fir
    7: ['Б', '302620'], # Береза - Birch
    8: ['ОС', '304000'], # Осина - Aspen
    9: ['Т', '304303', '304305', '304315'], # Тополь - Poplar
    10: ['ОЛХ', '504025', '304105'], # Ольха - Alder
    11: ['ИВ', '304403', '304410'], # Ива - Willow
    12: ['БК', '802694'], # Береза карликовая - Dwarf birch
    13: ['ИВК', '804330'], # Ива карликовая - Dwarf willow
}

In [25]:
def map_gdf(row, mapping, name):
    for i, l in mapping.items():
        if row[name] in l:
            return i
    raise Exception(row[name])

In [26]:
file['Species'] = file.apply(map_gdf, axis=1, mapping=specs, name='Vmr')

### Bon - forest productivity class

In [27]:
file["Bon"].unique()

array([51., 52.,  3.,  5.,  4.,  0.,  2.,  1., 12., 11.])

In [28]:
file["Bon"].value_counts()

Bon
5.0     547757
0.0     457515
4.0     377035
51.0    237397
52.0    132896
3.0     131605
12.0     14306
11.0     12543
2.0      12405
1.0        222
Name: count, dtype: int64

In [29]:
bons = {
    1: [0.],
    2: [52.],
    3: [51.],
    4: [5.],
    5: [4.],
    6: [3.],
    7: [2.],
    8: [12.],
    9: [11., 1.],
}

In [30]:
file['Bonity'] = file.apply(map_gdf, axis=1, mapping=bons, name='Bon')

### Mtip - forest type

In [31]:
file["Mtip"].unique()

array(['КСФ', 'ОСКСФ', 'ЗМТЯГ', 'БГБР', 'ТРБ', 'ДМХВ', 'ОССФ', '00000',
       'ПР', 'КЛШ', 'ЕРН', 'БГБРМ', 'ТБ', 'КРТ', 'БРБГМ', 'ХВ', 'БР', 'П',
       'ЗММТ', 'МШ', 'ЛШ', 'ЗМЯГ', '0', 'МШЯГ', 'ДМСФ', 'КМ', 'БГРМ',
       'ЗММЯГ', 'КОССФ', 'БРБГ', 'НГ', 'МШРТ', 'ХВМШ', 'РТ', 'ОСЕРН',
       'БГБГМ', '00', 'ЧР', 'ЛШБР', 'МШМП', 'Ч', 'мшяг', 'КООСФ', 'ос',
       'СФ', 'БГГБР', 'ОЛ', 'ЛБР', 'МЛК', 'ДМ', 'ЛОГ', 'мш', 'БРГБМ',
       'ГБМ', 'БРБМ', 'ЗМРТ', 'брбгм', 'нГ', 'ОСЕРн', 'КТРМШ', 'ХВП',
       'МШХВ', 'ШТ', 'МЯ', '0000000', 'ЕРн', 'ХВОСФ', 'В', 'КООССФ', 'О',
       'хв', 'ЗЯ', 'Л', '0000', '2', 'ЗМ', 'ЗМЯ', 'БРБ', 'ЗММ', 'ОСС',
       'ДМХ', 'БГБ', 'ЛШБ', 'ХВОС', 'ББР', 'БСФ', 'ДСФ', 'Д', 'РТВ',
       'ЛБХВ', 'лшбр', 'ДЬХВ', 'ксф', 'бр', 'ЧКС', 'ТР', 'ЗЯГ', 'ОС',
       'КС', 'БГ', 'БО', 'КЛ', 'клш', 'КССФ', 'БРЯГ', 'змяг', 'ЧЗМ',
       'ХДГ', 'КЧДГ', 'КЧЗМ', 'МТЗМ', 'КЧСФ', 'БРЛШ', 'БРЗМ', 'ЯЗ', 'ЧЗ',
       'ОСДГ', 'ХЗМ', 'ЛШЗМ', 'ЗМСФ', 'КЗМ', 'КЧЛШ', 'БЗ', 'КТЗМ', 'ЛШСФ',
       'БС', 'МЗ', 'ПМ', 'БЛ', 'ХВЗМ', 'ПП', 'ОККСФ'], dtype=object)

In [32]:
types = {
    1: ['', '0', '00', '00000', '0000000', '0000', '2'],
    2: ['КЛШ', 'ЛШ', 'НГ', 'нГ', 'В', 'Л', 'КЛ', 'клш'], # Нагорная Highland 1
    3: ['БГБР', 'БР', 'ЧР', 'ЛШБР', 'Ч', 'БГГБР', 'ЛБР', 'МЛК', 'ЛОГ', 'БГБ', 'ЛШБ', 'ББР', 'лшбр', 'бр', 'БРЛШ', 'БЛ'], # Брусничная Cowberry 2
    4: ['ЗМТЯГ', 'ЗМЯГ', 'МШЯГ', 'КМ', 'ЗММЯГ', 'мшяг', 'МЯ', 'ЗЯ', 'ЗМЯ', 'ЗЯГ', 'БРЯГ', 'змяг', 'БРЗМ', 'ЯЗ', 'ЧЗ', 'КЗМ', 'КЧЛШ', 'БЗ'], # Ягодниково-зеленомошная Berry-green-moss 3
    5: ['ЗММТ', 'ЗМ', 'ЗММ', 'ЧЗМ', 'КЧЗМ', 'МТЗМ', 'ХЗМ', 'ЛШЗМ', 'МЗ', 'ПМ', 'ХВЗМ'], # Травяно-зеленомошная Grass-green-moss 4
    6: ['МШРТ', 'РТ', 'МШМП', 'ЗМРТ', 'РТВ', 'ПП'], # Разнотравная Mixed herbs 5
    7: ['ПР', 'КРТ', 'П', 'КТРМШ', 'ХВП', 'ШТ', 'КТЗМ'], # Крупнотравно-приручьевая Tall-grass-riparian 7
    8: ['ДМХВ', 'БГБРМ', 'БРБГМ', 'ХВ', 'МШ', 'БГРМ', 'БРБГ', 'ХВМШ', 'БГБГМ', 'ос', 'ДМ', 'мш', 'БРГБМ', 'ГБМ', 'БРБМ', 'брбгм', 'МШХВ', 'О', 'хв', 'БРБ', 'ДМХ', 'ХВОС', 'Д', 'ЛБХВ', 'ДЬХВ', 'ОС', 'БГ', 'БО', 'ХДГ', 'КЧДГ', 'ОСДГ'], # Долгомошно-хвощевая Long-moss-horsetail 8
    9: ['КСФ', 'ОСКСФ', 'ТРБ', 'ОССФ', 'ТБ', 'ДМСФ', 'КОССФ', 'КООСФ', 'СФ', 'ХВОСФ', 'КООССФ', 'ОСС', 'БСФ', 'ДСФ', 'ксф', 'ЧКС', 'ТР', 'КС', 'КССФ', 'КЧСФ', 'ЗМСФ', 'ЛШСФ', 'БС', 'ОККСФ'], # Торфяно-болотная и сфагновая Peatland-sphagnum 9
    10: ['ЕРН', 'ОЛ', 'ОСЕРН', 'ОСЕРн', 'ЕРн'], # Кустарниковая Shrub 6
}

In [33]:
file['Type'] = file.apply(map_gdf, axis=1, mapping=types, name='Mtip')

### Amz1 - forest age

In [38]:
file["Amz1"].unique()

array([135, 165,  75, 175, 145,  80, 235, 195,  65,  70, 115,   0, 140,
       155,  40, 225, 295, 150,  30,  15, 130,  60,  20, 205,  25, 185,
        95, 245, 255,  10, 125, 100,  90,  85, 215, 275, 160,  35, 105,
        55, 110, 170, 180,   5,   2,   3,  45,  50, 285,  22, 120, 265,
        18, 200, 300, 230, 305, 190,  27,  28, 240, 250,  26, 325, 270,
       335, 210, 260, 315, 345, 220, 375, 355,  34,  23,  14,  12, 310,
        21, 280, 290, 208, 385,  19, 365,  46,   4,   6,  47,  41,  29,
        49,  44,  42,  13,  17,  48,  39,  33,  24,   9,  36,  37,  38,
        51,  32,  16,   7,  31,  54,  53,  11,  43,   1, 340, 320, 350,
        52, 360,   8, 330, 380,  89, 370,  56,  57, 117,  58,  63,  72,
        61,  62, 400,  59, 390, 142,  64,  66, 126, 136, 109], dtype=int32)

In [46]:
file["Amz1"].unique().max()

np.int32(400)

In [47]:
file["Age"] = file["Amz1"] / 500

### Tur1h1 - growing stock

In [49]:
file["Tur1h1"].unique()

array([100,  90,  25, 250,  35, 165,  45,  60,  55, 120,  70,   0, 125,
       140, 130,  15,  65, 180, 145, 185, 105,  80, 110,  10,  50, 170,
       160,  40,  75, 190,  85,  95,  20, 200, 115, 240, 150, 175, 205,
        30, 215, 135, 210, 260, 220,   5, 320, 230, 195, 155, 270, 285,
       325, 255,   7, 235, 275, 290, 245, 225, 265, 315, 480, 330, 280,
       350, 295, 335, 300, 340, 305, 445,   4, 410, 310, 370, 360, 365,
       440, 375, 390,   1,   6, 420,   8, 380,  12, 400, 500, 101, 450,
         2, 470,  24,  54,  28, 535,   3, 475, 248, 138,  57, 383, 191,
       127, 366, 177, 169, 279, 208, 212, 224, 373, 109, 124, 207, 166,
       414, 211, 447, 402,  58,  64,  98,  42, 176, 273,  81, 222, 229,
       271, 134, 183, 142, 268, 232, 153, 146, 331, 179, 206,  72, 178,
       198,  74, 313, 172, 186, 193,  29, 292, 168, 154,  11,  91, 164,
        49,  43, 192,  92, 137, 149,  78, 116,  94, 113,  93,  32, 174,
        88,  52, 158, 228, 277,  31, 203, 121,  68,   9,  46,  18,  23,
        33, 219,  96, 136,  61,  13, 173, 199, 249, 214,  97, 196,  39,
        48, 184, 262,  62,  86,  27, 148, 187, 201, 244,  71, 194,  82,
       239, 258, 276, 261, 293, 241, 126, 161, 296, 287, 231, 357, 351,
       209, 246,  37, 112, 119,  36,  56, 144, 151,  34, 141,  16, 162,
        26, 238,  99,  38,  83,  21, 122, 254,  84, 354, 288, 111, 163,
        47, 114,  73, 182,  51, 131, 152,  77, 242, 102,  69, 107,  22,
       197, 233, 128,  44,  41, 272, 216,  89,  76, 123, 106,  53,  63,
        87, 104, 139, 132, 274, 286, 266, 298, 181, 269, 282, 204, 323,
       251, 539, 284, 227, 223, 291, 171, 386, 478, 377, 311, 309, 143,
       326, 221, 252, 236, 318, 509,  59, 431, 133, 332, 415, 247, 336,
       338, 283, 314, 307, 281, 371, 278, 317,  67, 159,  19, 382, 430,
        66, 595, 118, 108, 356, 407, 355, 345, 156, 378, 465,  14, 202,
       358, 267, 329, 417, 297, 425, 395, 460, 510, 490, 505, 550, 385,
       405, 520], dtype=int32)

In [50]:
file["Tur1h1"].unique().max()

np.int32(595)

In [51]:
file["Volume"] = file["Tur1h1"] / 1000

In [52]:
file.head()

,SRI,Lr,MU,GIR,Ugir,Mk,Rel,Kv,Sknr,Pl,...,Skal1,Tur1h1,Strata,Izm,geometry,Species,Bonity,Type,Age,Volume
0,87,14,3,3,2,305000,1,335,6.0,3.1,...,0.6,100,12,0,"MULTIPOLYGON (((62.33137 63.80387, 62.33062 63...",2,3,9,0.27,0.100
1,87,15,4,6,14,204100,1,81,35.0,9.5,...,0.5,90,12,0,"MULTIPOLYGON (((64.88972 59.42719, 64.88878 59...",2,3,9,0.33,0.090
2,87,15,4,6,14,204100,1,79,43.0,22.6,...,0.4,25,6,0,"MULTIPOLYGON (((64.78062 59.4423, 64.78328 59....",2,2,9,0.15,0.025
3,87,15,4,6,14,204100,1,80,39.0,4.6,...,0.6,250,20,0,"MULTIPOLYGON (((64.82868 59.42363, 64.82945 59...",6,6,4,0.35,0.250
4,87,14,3,3,2,305000,1,333,5.0,7.9,...,0.4,35,12,0,"MULTIPOLYGON (((62.24469 63.80196, 62.2441 63....",2,2,9,0.27,0.035

In [53]:
file.to_file("hmao_forestry_values.gpkg")

## Exploratory data analysis and cleaning

In [2]:
file = gpd.read_file("hmao_forestry_values.gpkg")

At the beginning we had 1,923,681 objects in our database.

In [3]:
file.shape

(1923681, 27)

### Fires

Here we filter out the areas that were exposed to fires in last 40 years, but have age more than 40 years according to forestry data.

We got info about fires by calculating dNBR from our landsat data and removing the noize.

In [3]:
fires = gpd.read_file("fires_mask.gpkg")

In [4]:
file["idx"] = file.index

In [5]:
file['orig_area'] = file.to_crs(32642).geometry.area

In [6]:
intersections = gpd.overlay(file, fires.to_crs(file.crs), how='intersection')

In [7]:
intersections['intersect_area'] = intersections.to_crs(32642).geometry.area

In [8]:
intersections['overlap_ratio'] = intersections['intersect_area'] / intersections['orig_area']

In [9]:
result = intersections[(intersections['overlap_ratio'] >= 0.5) & (intersections['Amz1'] > 40)]

In [11]:
file = file.loc[~file["idx"].isin(result["idx"])]

In [13]:
file = file.drop(columns=['idx', 'orig_area'])

In [14]:
file.head()

,SRI,Lr,MU,GIR,Ugir,Mk,Rel,Kv,Sknr,Pl,...,Skal1,Tur1h1,Strata,Izm,Species,Bonity,Type,Age,Volume,geometry
0,87,14,3,3,2,305000,1,335,6.0,3.1,...,0.6,100,12,0,2,3,9,0.27,0.100,"MULTIPOLYGON (((62.33137 63.80387, 62.33062 63..."
2,87,15,4,6,14,204100,1,79,43.0,22.6,...,0.4,25,6,0,2,2,9,0.15,0.025,"MULTIPOLYGON (((64.78062 59.4423, 64.78328 59...."
3,87,15,4,6,14,204100,1,80,39.0,4.6,...,0.6,250,20,0,6,6,4,0.35,0.250,"MULTIPOLYGON (((64.82868 59.42363, 64.82945 59..."
4,87,14,3,3,2,305000,1,333,5.0,7.9,...,0.4,35,12,0,2,2,9,0.27,0.035,"MULTIPOLYGON (((62.24469 63.80196, 62.2441 63...."
5,87,14,3,3,2,305000,1,339,4.0,26.1,...,0.8,165,11,0,2,4,3,0.29,0.165,"MULTIPOLYGON (((62.45369 63.80399, 62.45435 63..."

In [5]:
file.shape

(1801947, 27)

In [15]:
file.to_file("hmao_forestry_values_filtered.gpkg")

### Invalid data

Here we filter out the objects that have invalid information - for example, tree species is not set, while other parameters show that it is a forested area.

In [2]:
file = gpd.read_file("hmao_forestry_values_filtered.gpkg")

In [3]:
file.head()

,SRI,Lr,MU,GIR,Ugir,Mk,Rel,Kv,Sknr,Pl,...,Skal1,Tur1h1,Strata,Izm,Species,Bonity,Type,Age,Volume,geometry
0,87,14,3,3,2,305000,1,335,6.0,3.1,...,0.6,100,12,0,2,3,9,0.27,0.100,"MULTIPOLYGON (((62.33137 63.80387, 62.33062 63..."
1,87,15,4,6,14,204100,1,79,43.0,22.6,...,0.4,25,6,0,2,2,9,0.15,0.025,"MULTIPOLYGON (((64.78062 59.4423, 64.78328 59...."
2,87,15,4,6,14,204100,1,80,39.0,4.6,...,0.6,250,20,0,6,6,4,0.35,0.250,"MULTIPOLYGON (((64.82868 59.42363, 64.82945 59..."
3,87,14,3,3,2,305000,1,333,5.0,7.9,...,0.4,35,12,0,2,2,9,0.27,0.035,"MULTIPOLYGON (((62.24469 63.80196, 62.2441 63...."
4,87,14,3,3,2,305000,1,339,4.0,26.1,...,0.8,165,11,0,2,4,3,0.29,0.165,"MULTIPOLYGON (((62.45369 63.80399, 62.45435 63..."

In [4]:
file.columns

Index(['SRI', 'Lr', 'MU', 'GIR', 'Ugir', 'Mk', 'Rel', 'Kv', 'Sknr', 'Pl', 'Zk',
       'Vmr', 'Amz1', 'Akl', 'Bon', 'Mtip', 'Dtg', 'Skal1', 'Tur1h1', 'Strata',
       'Izm', 'Species', 'Bonity', 'Type', 'Age', 'Volume', 'geometry'],
      dtype='object')

In [5]:
file.shape

(1801947, 27)

In [6]:
# Tree species is set, while one of the other parameters show that it is a non-forest area
file = file[~((file["Species"] != 1) & ((file["Bonity"] == 1) | (file["Type"] == 1) | (file["Age"] == 0) | (file["Volume"] == 0)))]

In [7]:
file.shape

(1781014, 27)

In [8]:
# Forest productivity class is set, while one of the other parameters show that it is a non-forest area
file = file[~((file["Bonity"] != 1) & ((file["Species"] == 1) | (file["Type"] == 1) | (file["Age"] == 0) | (file["Volume"] == 0)))]

In [9]:
file.shape

(1779682, 27)

In [10]:
# Forest type is set, while one of the other parameters show that it is a non-forest area
file = file[~((file["Type"] != 1) & ((file["Species"] == 1) | (file["Bonity"] == 1) | (file["Age"] == 0) | (file["Volume"] == 0)))]

In [11]:
file.shape

(1779670, 27)

In [12]:
# Age is non-zero, while one of the other parameters show that it is a non-forest area
file = file[~((file["Age"] != 0) & ((file["Species"] == 1) | (file["Bonity"] == 1) | (file["Type"] == 1) | (file["Volume"] == 0)))]

In [13]:
file.shape

(1779327, 27)

In [14]:
# Growing stock is non-zero, while one of the other parameters show that it is a non-forest area
file = file[~((file["Volume"] != 0) & ((file["Species"] == 1) | (file["Bonity"] == 1) | (file["Type"] == 1) | (file["Age"] == 0)))]

In [15]:
file.shape

(1779311, 27)

In [16]:
file.head()

,SRI,Lr,MU,GIR,Ugir,Mk,Rel,Kv,Sknr,Pl,...,Skal1,Tur1h1,Strata,Izm,Species,Bonity,Type,Age,Volume,geometry
0,87,14,3,3,2,305000,1,335,6.0,3.1,...,0.6,100,12,0,2,3,9,0.27,0.100,"MULTIPOLYGON (((62.33137 63.80387, 62.33062 63..."
1,87,15,4,6,14,204100,1,79,43.0,22.6,...,0.4,25,6,0,2,2,9,0.15,0.025,"MULTIPOLYGON (((64.78062 59.4423, 64.78328 59...."
2,87,15,4,6,14,204100,1,80,39.0,4.6,...,0.6,250,20,0,6,6,4,0.35,0.250,"MULTIPOLYGON (((64.82868 59.42363, 64.82945 59..."
3,87,14,3,3,2,305000,1,333,5.0,7.9,...,0.4,35,12,0,2,2,9,0.27,0.035,"MULTIPOLYGON (((62.24469 63.80196, 62.2441 63...."
4,87,14,3,3,2,305000,1,339,4.0,26.1,...,0.8,165,11,0,2,4,3,0.29,0.165,"MULTIPOLYGON (((62.45369 63.80399, 62.45435 63..."

In [17]:
file.shape

(1779311, 27)

In [18]:
# Identified as changed, but age higher than 50 years
file = file[~((file["Izm"] == 1) & (file["Amz1"] > 50))]

In [19]:
file.shape

(1778513, 27)

### Data that is probably invalid

Parameter combinations that are very unlikely to appear in the nature.

In [20]:
# High bonity, but low volume
file = file[~((file["Bonity"] <= 4) & (file["Volume"] >= 0.5))]

In [21]:
file.shape

(1778513, 27)

In [22]:
# Low bonity, but high volume
file = file[~((file["Bonity"] >= 8) & (file["Volume"] <= 0.5))]

In [23]:
file.shape

(1754909, 27)

In [24]:
# Birches and aspens tend to to be replaced after 100-150 years
file = file[~((file["Species"].isin([7, 8, 9, 10])) & (file["Amz1"] > 150))]

In [25]:
file.shape

(1738278, 27)

In [26]:
# Old forests with very low volume
file = file[~((file["Volume"] < 0.005) & (file["Amz1"] > 5))]

In [27]:
file.shape

(1738138, 27)

In [28]:
# Very young forests with high volume
file = file[~((file["Volume"] > 0.01) & (file["Amz1"] < 5))]

In [29]:
file.shape

(1738132, 27)

### Wrong strata

Data where strata differs from other forest parameters that define the strata.

In [30]:
u = file["Strata"].unique()
u.sort()
u

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 49, 50], dtype=int32)

In [31]:
# Strata 1 are non-forested areas
file = file[~((file["Strata"] == 1) & (file["Species"] != 1))]

In [32]:
file.shape

(1734480, 27)

In [33]:
# Strata 2 are young trees
file = file[~((file["Strata"] == 2) & (file["Amz1"] > 30))]

In [34]:
file.shape

(1711447, 27)

In [35]:
# Strata 3 are young trees
file = file[~((file["Strata"] == 3) & (file["Amz1"] > 25))]

In [36]:
file.shape

(1706227, 27)

In [37]:
# Strata 4 are middle-age high-bonity pine, larch, cedar
file = file[~((file["Strata"] == 4) & ~((file["Akl"].isin([3, 4])) & (file["Bonity"].isin([7, 8, 9])) & file["Species"].isin([2, 3, 4])))]

In [38]:
file.shape

(1706227, 27)

In [39]:
# Strata 5 are middle-age mid-bonity pine, larch, cedar
file = file[~((file["Strata"] == 5) & ~((file["Akl"].isin([3, 4])) & (file["Bonity"].isin([4, 5, 6])) & file["Species"].isin([2, 3, 4])))]

In [40]:
file.shape

(1706227, 27)

In [41]:
# Strata 6 are middle-age low-bonity pine, larch, cedar
file = file[~((file["Strata"] == 6) & ~((file["Akl"].isin([3, 4])) & (file["Bonity"].isin([2, 3])) & file["Species"].isin([2, 3, 4])))]

In [42]:
file.shape

(1706227, 27)

In [43]:
# Strata 7 are old high-bonity pine, larch, cedar
file = file[~((file["Strata"] == 7) & ~((file["Akl"].isin([5])) & (file["Bonity"].isin([7, 8, 9])) & file["Species"].isin([2, 3, 4])))]

In [44]:
file.shape

(1706227, 27)

In [45]:
# Strata 8 are old mid-bonity pine, larch, cedar
file = file[~((file["Strata"] == 8) & ~((file["Akl"].isin([5])) & (file["Bonity"].isin([4, 5, 6])) & file["Species"].isin([2, 3, 4])))]

In [46]:
file.shape

(1706225, 27)

In [47]:
# Strata 9 are old low-bonity pine, larch, cedar
file = file[~((file["Strata"] == 9) & ~((file["Akl"].isin([5])) & (file["Bonity"].isin([2, 3])) & file["Species"].isin([2, 3, 4])))]

In [48]:
file.shape

(1663206, 27)

In [49]:
# Strata 10 are very old high-bonity pine, larch, cedar
file = file[~((file["Strata"] == 10) & ~((file["Akl"] >= 6) & (file["Bonity"].isin([7, 8, 9])) & file["Species"].isin([2, 3, 4])))]

In [50]:
file.shape

(1663206, 27)

In [51]:
# Strata 11 are very old mid-bonity pine, larch, cedar
file = file[~((file["Strata"] == 11) & ~((file["Akl"] >= 6) & (file["Bonity"].isin([4, 5, 6])) & file["Species"].isin([2, 3, 4])))]

In [52]:
file.shape

(1663206, 27)

In [53]:
# Strata 12 are very old low-bonity pine, larch, cedar
file = file[~((file["Strata"] == 12) & ~((file["Akl"] >= 6) & (file["Bonity"].isin([2, 3])) & file["Species"].isin([2, 3, 4])))]

In [54]:
file.shape

(1663206, 27)

In [55]:
# Strata 13 are middle-age high-bonity spruce, fir
file = file[~((file["Strata"] == 13) & ~((file["Akl"].isin([3, 4])) & (file["Bonity"].isin([7, 8, 9])) & file["Species"].isin([5, 6])))]

In [56]:
file.shape

(1663206, 27)

In [57]:
# Strata 14 are middle-age mid-bonity spruce, fir
file = file[~((file["Strata"] == 14) & ~((file["Akl"].isin([3, 4])) & (file["Bonity"].isin([4, 5, 6])) & file["Species"].isin([5, 6])))]

In [58]:
file.shape

(1663206, 27)

In [59]:
# Strata 15 are middle-age low-bonity spruce, fir
file = file[~((file["Strata"] == 15) & ~((file["Akl"].isin([3, 4])) & (file["Bonity"].isin([2, 3])) & file["Species"].isin([5, 6])))]

In [60]:
file.shape

(1663206, 27)

In [61]:
# Strata 16 are old high-bonity spruce, fir
file = file[~((file["Strata"] == 16) & ~((file["Akl"].isin([5])) & (file["Bonity"].isin([7, 8, 9])) & file["Species"].isin([5, 6])))]

In [62]:
file.shape

(1663206, 27)

In [63]:
# Strata 17 are old mid-bonity spruce, fir
file = file[~((file["Strata"] == 17) & ~((file["Akl"].isin([5])) & (file["Bonity"].isin([4, 5, 6])) & file["Species"].isin([5, 6])))]

In [64]:
file.shape

(1663206, 27)

In [65]:
# Strata 18 are old low-bonity spruce, fir
file = file[~((file["Strata"] == 18) & ~((file["Akl"].isin([5])) & (file["Bonity"].isin([2, 3])) & file["Species"].isin([5, 6])))]

In [66]:
file.shape

(1663206, 27)

In [67]:
# Strata 19 are very old high-bonity spruce, fir
file = file[~((file["Strata"] == 19) & ~((file["Akl"] >= 6) & (file["Bonity"].isin([7, 8, 9])) & file["Species"].isin([5, 6])))]

In [68]:
file.shape

(1663206, 27)

In [69]:
# Strata 20 are very old mid-bonity spruce, fir
file = file[~((file["Strata"] == 20) & ~((file["Akl"] >= 6) & (file["Bonity"].isin([4, 5, 6])) & file["Species"].isin([5, 6])))]

In [70]:
file.shape

(1663206, 27)

In [71]:
# Strata 21 are very old low-bonity spruce, fir
file = file[~((file["Strata"] == 21) & ~((file["Akl"] >= 6) & (file["Bonity"].isin([2, 3])) & file["Species"].isin([5, 6])))]

In [72]:
file.shape

(1663206, 27)

In [73]:
# Strata 22 are middle-age high-bonity aspen, alder, poplar, willow
file = file[~((file["Strata"] == 22) & ~((file["Akl"].isin([3])) & (file["Bonity"].isin([7, 8, 9])) & file["Species"].isin([8, 9, 10, 11])))]

In [74]:
file.shape

(1663206, 27)

In [75]:
# Strata 23 are middle-age mid-bonity aspen, alder, poplar, willow
file = file[~((file["Strata"] == 23) & ~((file["Akl"].isin([3])) & (file["Bonity"].isin([4, 5, 6])) & file["Species"].isin([8, 9, 10, 11])))]

In [76]:
file.shape

(1663206, 27)

In [77]:
# Strata 24 are middle-age low-bonity aspen, alder, poplar, willow
file = file[~((file["Strata"] == 24) & ~((file["Akl"].isin([3])) & (file["Bonity"].isin([2, 3])) & file["Species"].isin([8, 9, 10, 11])))]

In [78]:
file.shape

(1663206, 27)

In [79]:
# Strata 25 are old high-bonity aspen, alder, poplar, willow
file = file[~((file["Strata"] == 25) & ~((file["Akl"].isin([4])) & (file["Bonity"].isin([7, 8, 9])) & file["Species"].isin([8, 9, 10, 11])))]

In [80]:
file.shape

(1663206, 27)

In [81]:
# Strata 26 are old mid-bonity aspen, alder, poplar, willow
file = file[~((file["Strata"] == 26) & ~((file["Akl"].isin([4])) & (file["Bonity"].isin([4, 5, 6])) & file["Species"].isin([8, 9, 10, 11])))]

In [82]:
file.shape

(1663206, 27)

In [83]:
# Strata 27 are old low-bonity aspen, alder, poplar, willow
file = file[~((file["Strata"] == 27) & ~((file["Akl"].isin([4])) & (file["Bonity"].isin([2, 3])) & file["Species"].isin([8, 9, 10, 11])))]

In [84]:
file.shape

(1663206, 27)

In [85]:
# Strata 28 are very old high-bonity aspen, alder, poplar, willow
file = file[~((file["Strata"] == 28) & ~((file["Akl"] >= 5) & (file["Bonity"].isin([7, 8, 9])) & file["Species"].isin([8, 9, 10, 11])))]

In [86]:
file.shape

(1663206, 27)

In [87]:
# Strata 29 are very old mid-bonity aspen, alder, poplar, willow
file = file[~((file["Strata"] == 29) & ~((file["Akl"] >= 5) & (file["Bonity"].isin([4, 5, 6])) & file["Species"].isin([8, 9, 10, 11])))]

In [88]:
file.shape

(1663206, 27)

In [89]:
# Strata 30 are very old low-bonity aspen, alder, poplar, willow
file = file[~((file["Strata"] == 30) & ~((file["Akl"] >= 5) & (file["Bonity"].isin([2, 3])) & file["Species"].isin([8, 9, 10, 11])))]

In [90]:
file.shape

(1663206, 27)

In [91]:
# Strata 31 are middle-age high-bonity birch, alder
file = file[~((file["Strata"] == 31) & ~((file["Akl"].isin([3, 4])) & (file["Bonity"].isin([7, 8, 9])) & file["Species"].isin([7, 10])))]

In [92]:
file.shape

(1663206, 27)

In [93]:
# Strata 32 are middle-age mid-bonity birch, alder
file = file[~((file["Strata"] == 32) & ~((file["Akl"].isin([3, 4])) & (file["Bonity"].isin([4, 5, 6])) & file["Species"].isin([7, 10])))]

In [94]:
file.shape

(1663206, 27)

In [95]:
# Strata 33 are middle-age low-bonity birch, alder
file = file[~((file["Strata"] == 33) & ~((file["Akl"].isin([3, 4])) & (file["Bonity"].isin([2, 3])) & file["Species"].isin([7, 10])))]

In [96]:
file.shape

(1663206, 27)

In [97]:
# Strata 34 are old high-bonity birch, alder
file = file[~((file["Strata"] == 34) & ~((file["Akl"].isin([5])) & (file["Bonity"].isin([7, 8, 9])) & file["Species"].isin([7, 10])))]

In [98]:
file.shape

(1663206, 27)

In [99]:
# Strata 35 are old mid-bonity birch, alder
file = file[~((file["Strata"] == 35) & ~((file["Akl"].isin([5])) & (file["Bonity"].isin([4, 5, 6])) & file["Species"].isin([7, 10])))]

In [100]:
file.shape

(1663206, 27)

In [101]:
# Strata 36 are old low-bonity birch, alder
file = file[~((file["Strata"] == 36) & ~((file["Akl"].isin([5])) & (file["Bonity"].isin([2, 3])) & file["Species"].isin([7, 10])))]

In [102]:
file.shape

(1663206, 27)

In [103]:
# Strata 37 are very old high-bonity birch, alder
file = file[~((file["Strata"] == 37) & ~((file["Akl"] >= 6) & (file["Bonity"].isin([7, 8, 9])) & file["Species"].isin([7, 10])))]

In [104]:
file.shape

(1663206, 27)

In [105]:
# Strata 38 are very old mid-bonity birch, alder
file = file[~((file["Strata"] == 38) & ~((file["Akl"] >= 6) & (file["Bonity"].isin([4, 5, 6])) & file["Species"].isin([7, 10])))]

In [106]:
file.shape

(1663206, 27)

In [107]:
# Strata 39 are very old low-bonity birch, alder
file = file[~((file["Strata"] == 39) & ~((file["Akl"] >= 6) & (file["Bonity"].isin([2, 3])) & file["Species"].isin([7, 10])))]

In [108]:
file.shape

(1663206, 27)

In [109]:
# Strata 49 are shrubs
file = file[~((file["Strata"] == 49) & ~(file["Species"].isin([10, 12, 13])))]

In [110]:
file.shape

(1663206, 27)

In [111]:
# Strata 50 are non-forested areas
file = file[~((file["Strata"] == 50) & ~(file["Species"].isin([1]) & file["Bonity"].isin([1]) & file["Type"].isin([1]) & (file["Age"] == 0) & (file["Volume"] == 0)))]

In [112]:
file.shape

(1663120, 27)

In [113]:
file.columns

Index(['SRI', 'Lr', 'MU', 'GIR', 'Ugir', 'Mk', 'Rel', 'Kv', 'Sknr', 'Pl', 'Zk',
       'Vmr', 'Amz1', 'Akl', 'Bon', 'Mtip', 'Dtg', 'Skal1', 'Tur1h1', 'Strata',
       'Izm', 'Species', 'Bonity', 'Type', 'Age', 'Volume', 'geometry'],
      dtype='object')

In [145]:
# High age class and low age
file = file[~((file["Akl"] > 10) & (file["Amz1"] < 100))]

In [157]:
file.shape

(1659992, 27)

In [158]:
file.to_file("hmao_forestry_values_filtered_int.gpkg")

### NDVI

Here we filter out the objects that have summer or winter NDVI not consistent with forest parameters

In [2]:
file = gpd.read_file("hmao_forestry_values_filtered_int.gpkg")

In [3]:
file.shape

(1659992, 27)

In [4]:
file.geometry = file.geometry.make_valid()

In [8]:
import rioxarray as rxr
from geocube.api.core import make_geocube

with rxr.open_rasterio(r"G:\Work\hmao-index\2024\summer\ndvi.tif") as ndvi:
    out_grid = make_geocube(
        vector_data=file.reset_index(),
        measurements=["index"],
        like=ndvi, # ensure the data are on the same grid
    )
    out_grid["ndvi"] = (ndvi.dims, ndvi.values, ndvi.attrs, ndvi.encoding)
    grouped_elevation = out_grid.drop_vars("spatial_ref").groupby(out_grid.index)
    grid_mean = grouped_elevation.mean().rename({"ndvi": "ndvi_s"}).to_dataframe()
    file = file.reset_index().merge(grid_mean, on="index", how="left").drop(columns=['index'])

C:\ProgramData\miniforge3\envs\geo\Lib\site-packages\xarray\structure\concat.py:540: UserWarning: No index created for dimension index because variable index is not a coordinate. To create an index for index, please first call `.set_coords('index')` on this object.
  ds.expand_dims(dim_name, create_index_for_new_dim=create_index_for_new_dim)

In [9]:
file.shape

(1659992, 28)

In [12]:
file["ndvi_s"] = file["ndvi_s"].fillna(0)

In [13]:
file.to_file("hmao_forestry_values_ndvi_s.gpkg")

In [2]:
file = gpd.read_file("hmao_forestry_values_ndvi_s.gpkg")

In [3]:
file.shape

(1659992, 28)

In [4]:
import rioxarray as rxr
from geocube.api.core import make_geocube

with rxr.open_rasterio(r"G:\Work\hmao-index\2024\winter\ndvi.tif") as ndvi:
    out_grid = make_geocube(
        vector_data=file.reset_index(),
        measurements=["index"],
        like=ndvi, # ensure the data are on the same grid
    )
    out_grid["ndvi"] = (ndvi.dims, ndvi.values, ndvi.attrs, ndvi.encoding)
    grouped_elevation = out_grid.drop_vars("spatial_ref").groupby(out_grid.index)
    grid_mean = grouped_elevation.mean().rename({"ndvi": "ndvi_w"}).to_dataframe()
    file = file.reset_index().merge(grid_mean, on="index", how="left").drop(columns=['index'])

C:\ProgramData\miniforge3\envs\geo\Lib\site-packages\xarray\structure\concat.py:540: UserWarning: No index created for dimension index because variable index is not a coordinate. To create an index for index, please first call `.set_coords('index')` on this object.
  ds.expand_dims(dim_name, create_index_for_new_dim=create_index_for_new_dim)

In [5]:
file.shape

(1659992, 29)

In [6]:
file["ndvi_w"] = file["ndvi_w"].fillna(0)

In [7]:
file.to_file("hmao_forestry_values_ndvi_w.gpkg")

In [2]:
file = gpd.read_file("hmao_forestry_values_ndvi_w.gpkg")

In [4]:
file.shape

(1659992, 29)

In [9]:
# Forested areas with low NDVI
file = file[~((file["Bonity"] != 1) & (file["ndvi_s"] < 0.6) & (file["ndvi_w"] < 0.25))]

In [10]:
file.shape

(1630853, 29)

In [12]:
# Forested areas with low NDVI
file = file[~((file["Bonity"] != 1) & (file["ndvi_s"] < 0.5))]

In [13]:
file.shape

(1630135, 29)

In [25]:
# Forested areas with low NDVI
file = file[~((file["Bonity"] != 1) & (file["Species"] < 7) & (file["ndvi_w"] < 0))]

In [26]:
file.shape

(1602269, 29)

In [30]:
# High-bonity areas with low NDVI
file = file[~((file["Bonity"] > 6) & (file["ndvi_s"] < 0.75))]

In [31]:
file.shape

(1602195, 29)

In [39]:
# High-bonity areas with low NDVI
file = file[~((file["Bonity"] > 6) & (file["Species"] < 7) & (file["ndvi_w"] < 0.5))]

In [40]:
file.shape

(1602009, 29)

In [46]:
# Med-high-bonity areas with low NDVI
file = file[~((file["Bonity"] > 4) & (file["ndvi_s"] < 0.65))]

In [47]:
file.shape

(1597556, 29)

In [49]:
# Med-high-bonity areas with low NDVI
file = file[~((file["Bonity"] > 4) & (file["Species"] < 7) & (file["ndvi_w"] < 0.25))]

In [50]:
file.shape

(1576028, 29)

In [62]:
# Non-forested areas with high NDVI
file = file[~((file["Bonity"] == 1) & (file["ndvi_s"] > 0.9) & (file["ndvi_w"] > 0.25))]

In [63]:
file.shape

(1574638, 29)

In [64]:
file.to_file("hmao_forestry_values_filtered_ndvi.gpkg")

In [2]:
file = gpd.read_file("hmao_forestry_values_filtered_ndvi.gpkg")

In [6]:
file.head()

,SRI,Lr,MU,GIR,Ugir,Mk,Rel,Kv,Sknr,Pl,...,Strata,Izm,Species,Bonity,Type,Age,Volume,ndvi_s,ndvi_w,geometry
0,87,14,3,3,2,305000,1,335,6.0,3.1,...,12,0,2,3,9,135.0,100.0,0.788378,0.366932,"MULTIPOLYGON (((62.33137 63.80387, 62.33062 63..."
1,87,15,4,6,14,204100,1,79,43.0,22.6,...,6,0,2,2,9,75.0,25.0,0.742923,0.092810,"MULTIPOLYGON (((64.78062 59.4423, 64.78328 59...."
2,87,15,4,6,14,204100,1,80,39.0,4.6,...,20,0,6,6,4,175.0,250.0,0.857134,0.575262,"MULTIPOLYGON (((64.82868 59.42363, 64.82945 59..."
3,87,14,3,3,2,305000,1,333,5.0,7.9,...,12,0,2,2,9,135.0,35.0,0.749790,0.193213,"MULTIPOLYGON (((62.24469 63.80196, 62.2441 63...."
4,87,14,3,3,2,305000,1,339,4.0,26.1,...,11,0,2,4,3,145.0,165.0,0.780530,0.363092,"MULTIPOLYGON (((62.45369 63.80399, 62.45435 63..."

Normalization is actually not needed, denormalize the data again.

In [4]:
file["Age"] *= 500

In [5]:
file["Volume"] *= 1000

In [7]:
file.to_file("hmao_forestry_values_filtered_denorm.gpkg")